### ISSUE TITLE
Windows or linux one 

### ISSUE THREAD

**Issue by chintan9** [bdash-app/bdash#11]
Can we have windows or linux app?

**Comment by hokaccha** [comment]
Not yet. I have a plan to make it available sometime soon.

**Comment by pedrodude** [comment]
Also interested in this, let me know if you need a tester!

**Comment by rabitarochan** [comment]
I confirmed that it works on Windows by cloning and building the code.

```
> git clone https://github.com/bdash-app/bdash.git

> cd bdash

> npm install

> npm install  --save-dev yarn

> notepad packages.json
..  add ["yarn": "yarn"] to `scripts`

> npm run build:sqlite3      # (*1)

> npm start
```

(*1): The `npm run build:sqlite3` command is required Python 2.7 in `C:\Python27` .

**Comment by chintan9** [comment]
thanks

**Comment by hokaccha** [comment]
@pedrodude @rabitarochan

I prepared a release for windows. Could you please try it?
https://github.com/bdash-app/bdash/releases/tag/1.2.0

**Comment by pedrodude** [comment]
The app starts fine; a bit slowly.  I don't currently have a supported DB on my system however, so I can't test features yet.  Is MS SQL Server compatibility on the roadmap?

I'm running Windows 8.1

**Comment by hokaccha** [comment]
@pedrodude Thank you for your checking!

> a bit slowly

That's right 😅

> Is MS SQL Server compatibility on the roadmap?

I added it! https://github.com/bdash-app/bdash/commit/b162fd8fbc7272dcf3f027dc05b343af05bf1ef4
