### ISSUE TITLE
Cannot open bdash on macOS Catalina

### ISSUE THREAD

**Issue by nekketsuuu** [bdash-app/bdash#119]
Due to the Apple Notary Service, I could not run bdash on macOS Catalina (version 10.15.4) by clicking the app icon on Launchpad. Could you notarize the bdash app?

More about nortarization: https://developer.apple.com/news/?id=10032019a

Workaround: Open `/Applications` by Finder. Right-click the app icon and click "Open", and then click "Open" again in a pop-up window. Once I opened bdash using this method, I can open bdash from Launchpad without any problems.

**Comment by hokaccha** [comment]
Fixed in v1.8.1
