### ISSUE TITLE
Strange behavior when X column is timestamptz in PostgreSQL (or Redshift)

### ISSUE THREAD

**Issue by eagletmt** [bdash-app/bdash#142]
When I run this query https://gist.github.com/eagletmt/d8542e841d679475ae27916985d66aec , the chart looks strange.
The left side of X column should be "2020-07-22 18:00:00+09" and the right side should be "2020-07-22 19:00:00+09".

**Comment by mtgto** [comment]
https://github.com/plotly/plotly.js/pull/5015
