### ISSUE TITLE
Bdash on the Electron website?

### ISSUE THREAD

**Issue by zeke** [bdash-app/bdash#15]
@watilde told me about this app today. I hadn't seen it before. Would you be interested in featuring it on the Electron website? If so, take a look at https://github.com/electron/electron-apps/blob/master/contributing.md

:v:

**Comment by hokaccha** [comment]
@zeke @watilde I sent the pull request to electron-apps. thanks!

**Comment by zeke** [comment]
Shipped!

**Comment by hokaccha** [comment]
🎉
