### ISSUE TITLE
sslmode=require on Heroku Postgres database

### ISSUE THREAD

**Issue by richardvenneman** [bdash-app/bdash#7]
Bdash looks awesome and I'd wish to use it with a Heroku database.

When performing a Connection Test on a Heroku Database, the following error is thrown:

> no pg_hba.conf entry for host "xx.xxx.xxx.xxx", user "xxxxxxxxx", database "xxxxxxxxx", SSL off

I suspect this has something to do with the SSL requirement. The [Heroku Postgres documentation](https://devcenter.heroku.com/articles/heroku-postgresql#external-connections-ingress) specifies that `sslmode=require` needs to be specified on the connection.

I don't think I can contribute in code but I will help out in any way I can 😄

**Comment by hotchpotch** [comment]
I impl => #13  👍

**Comment by hokaccha** [comment]
It's implemented by #13 (thanks to @hotchpotch) and released [v1.1.0](https://github.com/bdash-app/bdash/releases/tag/1.1.0).
